version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - dwh_network

  spark:
    build:
      context: ./spark_service
    container_name: spark_master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "8888:8888" 
    volumes:
      - ./notebooks:/home/jovyan/work 
    networks:
      - dwh_network
    depends_on:
      - postgres


volumes:
  postgres_data:

networks:
  dwh_network:
    driver: bridge